### ISSUE TITLE
integration expression tree node

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#111]
need to be able to define integrations over space of the form:
$$
f(x) = \int_0^x  f(x')dx'
$$

These will be replaced by a matrix-vector multiply by the discretisation

**Comment by tinosulzer** [comment]
@Scottmar93 should the integral for a spherical domain have a factor of 2*pi or not?

**Comment by Scottmar93** [comment]
> should the integral for a spherical domain have a factor of 2*pi or not?

I would put it in. 

If we are just integrating to determine conservation of mass it doesn't really matter. Total lithium-ions in the electrolyte should be conserved. Therefore total lithium in the electrode particles is conserved (and 2pi factor is in both negative and positive electrode particle integrals). 

If we want to output the total lithium in each electrode independently then it is probably clearer to put in the 2pi so we can say its the amount in the particles instead of the amount in a portion of the particle (I don't know how to refer to this properly).
