### ISSUE TITLE
refactor reaction diffusion model

### ISSUE THREAD

**Issue by martinjrobins** [tinosulzer/PyBaMM#17]
See #16. 

refactor the `ReactionDiffusionModel` class to inherit from `BaseModel` (see #19), implementing a reaction diffusion model

**Comment by Scottmar93** [comment]
It should be noted that this issue is different to #49 Refactor StefanMaxwellDiffusions Class. 

This issue assembles the `homogenous_reactions` function and `StefanMaxwellDiffusion` sub model to produce a reaction diffusion model in the electrolyte. The `StefanMaxwellDiffusion` and `homogenous_reaction` function will be used again in other models we develop.
