### ISSUE TITLE
Clean up parameters

### ISSUE THREAD

**Issue by tinosulzer** [tinosulzer/PyBaMM#177]
After discussions with @Scottmar93 and @rtimms we have come up with a set of parameters that is common to both lead-acid and lithium-ion models.

We now need to clean up the files `standard_parameters` and `standard_parameters_lead_acid` to use this common parameter framework. We should also use more informative names in the parameter strings as there is no reason to use an abbreviation there, e.g. 
```python3
c_max = Parameter("maximum electrolyte concentration")
```

**Comment by tinosulzer** [comment]
Some questions as I'm going along:
- Whether to use the module as a class, as we're currently doing, or use explicit classes
- How much to write in the API docs when the Parameter strings are already explicit (but combined parameters, e.g. dimensionless, don't get those explicit string names)

**Comment by Scottmar93** [comment]
I quite liked it being a module because we can just do:

```from pybamm.standard_parameters import ln, lp, gamma_n, etc```

if we use an explicit class then we either need to keep doing class.parameter which make the equations harder to read or write a big list of a=class.a etc which defeats the point.

I'm not sure on the API documentation. Is the goal of API documentation to only display the things needed to interact with the module (in which case we should just show the dimensionless parameters and hide the dimensional ones) or should it offer a complete description of everything within the function?

**Comment by Scottmar93** [comment]
We should also convert the submodels into the set of dimensionless parameters we agree upon. This might be a separate issue.

**Comment by tinosulzer** [comment]
@rtimms and/or @Scottmar93 could you take a look at this branch please and make sure I haven't messed up the lithium-ion parameters and models. Feel free to just pull the branch locally and make your own edits. See also comments in the code on some things I wasn't sure about

Note that I couldn't get the imports to work as suggested by Scott, which means it's still a bit messy in the submodels

**Comment by Scottmar93** [comment]
Happy to pick this up after I finish the 1vmany particles issue

**Comment by tinosulzer** [comment]
Making a PR for this, specific parameters can be updated within model issues
